[package]
name = "sm-sourcenav"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
name = "sourcenav"

[dependencies]
sm-ext = { version = "0.3.0", git = "https://github.com/asherkin/sm-ext-rs" }
sourcenav = "0.2.0"